/**
 * CSS custom properties.
 */

import type { Palette } from '../types.ts'
import { tokenName, formatOklch } from './shared.ts'

export interface CssOptions {
  selector?: string
  prefix?: string
  /**
   * `hex` is universally safe. `oklch` is exact but needs a modern browser.
   * `progressive` ships hex and upgrades to OKLCH where supported.
   */
  mode?: 'hex' | 'oklch' | 'progressive'
}

/**
 * Emit the palette as custom properties.
 *
 * Progressive mode uses an `@supports` block rather than the usual trick of
 * declaring the same property twice. That trick does not work for custom
 * properties: their values are not validated at parse time, so an older browser
 * accepts the `oklch()` declaration, discards the hex one it shadows, and then
 * fails at every `var()` that uses it — leaving the page unstyled rather than
 * falling back.
 */
export function exportCss(palette: Palette, options: CssOptions = {}): string {
  const selector = options.selector ?? ':root'
  const prefix = options.prefix ?? 'color'
  const mode = options.mode ?? 'progressive'

  const lines: string[] = [header(palette)]

  lines.push(`${selector} {`)
  for (const ramp of palette.ramps) {
    lines.push(`  /* ${rampComment(ramp)} */`)
    for (const swatch of ramp.swatches) {
      const value = mode === 'oklch' ? formatOklch(swatch.oklch) : swatch.hex
      const note = swatch.isSeed ? ' /* your colour, unchanged */' : ''
      lines.push(`  --${tokenName(prefix, ramp.name, swatch.label)}: ${value};${note}`)
    }
  }
  lines.push('}')

  if (mode === 'progressive') {
    lines.push('')
    lines.push('/* Wider-gamut displays get the exact colours the palette was solved in. */')
    lines.push('@supports (color: oklch(50% 0 0)) {')
    lines.push(`  ${selector} {`)
    for (const ramp of palette.ramps) {
      for (const swatch of ramp.swatches) {
        lines.push(
          `    --${tokenName(prefix, ramp.name, swatch.label)}: ${formatOklch(swatch.oklch)};`,
        )
      }
    }
    lines.push('  }')
    lines.push('}')
  }

  return lines.join('\n') + '\n'
}

function header(palette: Palette): string {
  const { sharedPairTable } = palette
  const aa = sharedPairTable.find((entry) => entry.minWcag >= 4.5)
  const aaLarge = sharedPairTable.find((entry) => entry.minWcag >= 3)

  const rules = [
    aaLarge
      ? `   - ${aaLarge.distance} steps apart or more: at least 3:1 (large text, icons, borders)`
      : null,
    aa ? `   - ${aa.distance} steps apart or more: at least 4.5:1 (body text)` : null,
  ].filter(Boolean)

  return [
    '/*',
    ' * Generated by Science Color Palette.',
    ' *',
    ' * Every ramp shares one lightness scale, so the same shade number carries the',
    ' * same contrast in every hue. Which means:',
    ...rules,
    ' *',
    ' * Those hold for any pair of shades from any two ramps below.',
    ' */',
    '',
  ].join('\n')
}

function rampComment(ramp: Palette['ramps'][number]): string {
  const parts = [ramp.name]

  if (ramp.seed) {
    parts.push(
      ramp.seed.mode === 'exact'
        ? `from ${ramp.seed.input}, kept exactly at ${ramp.seed.slotLabel}`
        : `from ${ramp.seed.input}, harmonized at ${ramp.seed.slotLabel}`,
    )
  }

  if (!ramp.report.usesSharedLadder) {
    parts.push('own lightness scale')
  }

  return parts.join(' — ')
}
