/**
 * W3C Design Tokens format.
 *
 * The interchange format design-tool pipelines are converging on. The colour
 * value is written as a structured object rather than a hex string, which the
 * draft spec prefers because it can carry a colour space; a hex string is kept
 * alongside for tools that only read that, and `legacyHexValue` switches to the
 * older string form entirely.
 *
 * The contrast measurements and the OKLCH coordinates travel in `$extensions`,
 * so a pipeline can act on them — pick the first shade clearing 4.5:1, say —
 * rather than re-deriving what the generator already computed.
 */

import type { Palette, Swatch } from '../types.ts'
import { slug } from './shared.ts'

const NAMESPACE = 'dev.sciencecolorpalette'

export interface DtcgOptions {
  /** Emit `$value` as a plain hex string, for older tooling. */
  legacyHexValue?: boolean
}

export function exportDtcg(palette: Palette, options: DtcgOptions = {}): unknown {
  const color: Record<string, unknown> = {}

  for (const ramp of palette.ramps) {
    const group: Record<string, unknown> = {
      $type: 'color',
      $description: describeRamp(ramp),
    }

    for (const swatch of ramp.swatches) {
      group[String(swatch.label)] = token(swatch, options)
    }

    color[slug(ramp.name)] = group
  }

  return {
    $description:
      'Generated by Science Color Palette. Every ramp shares one lightness scale, ' +
      'so a given shade number carries the same contrast in every hue.',
    color,
    $extensions: {
      [NAMESPACE]: {
        engineVersion: palette.meta.engineVersion,
        algorithmVersion: palette.meta.algorithmVersion,
        gamut: palette.meta.gamut,
        stepDistanceGuarantees: palette.sharedPairTable.map((entry) => ({
          distance: entry.distance,
          minWcagRatio: entry.minWcag,
          minApcaLc: entry.minApcaLc,
        })),
      },
    },
  }
}

function token(swatch: Swatch, options: DtcgOptions): unknown {
  return {
    $value: options.legacyHexValue
      ? swatch.hex
      : {
          colorSpace: 'srgb',
          components: [
            round(swatch.rgb.r / 255, 6),
            round(swatch.rgb.g / 255, 6),
            round(swatch.rgb.b / 255, 6),
          ],
          alpha: 1,
          hex: swatch.hex,
        },
    $extensions: {
      [NAMESPACE]: {
        oklch: [round(swatch.oklch.l, 6), round(swatch.oklch.c, 6), round(swatch.oklch.h, 4)],
        relativeLuminance: round(swatch.wcag.y, 6),
        isSeed: swatch.isSeed,
        wcag: {
          onWhite: round(swatch.wcag.onWhite, 4),
          onBlack: round(swatch.wcag.onBlack, 4),
        },
        apca: {
          asTextOnWhite: round(swatch.apca.asTextOnWhite, 2),
          asTextOnBlack: round(swatch.apca.asTextOnBlack, 2),
        },
        onColor: swatch.onHex,
        ...(swatch.guarantees.length > 0 ? { guarantees: swatch.guarantees } : {}),
      },
    },
  }
}

function describeRamp(ramp: Palette['ramps'][number]): string {
  const parts: string[] = []

  if (ramp.seed) {
    parts.push(
      ramp.seed.mode === 'exact'
        ? `Built around ${ramp.seed.input}, kept exactly at shade ${ramp.seed.slotLabel}.`
        : `Harmonized from ${ramp.seed.input}, nearest shade ${ramp.seed.slotLabel}.`,
    )
  }

  if (!ramp.report.usesSharedLadder) {
    parts.push('Uses its own lightness scale, so shade numbers are not comparable to other ramps.')
  }

  if (ramp.report.brokenGuarantees.length > 0) {
    parts.push(
      'Shades below the usual contrast for their position: ' +
        ramp.report.brokenGuarantees
          .map((b) => `${b.label} (${b.actual}:1, expected ${b.target}:1)`)
          .join(', ') +
        '.',
    )
  }

  return parts.join(' ') || `The ${ramp.name} ramp.`
}

function round(value: number, places: number): number {
  const factor = 10 ** places
  return Math.round(value * factor) / factor
}
