/**
 * Tailwind CSS v4 theme block.
 *
 * v4 configures colours in CSS rather than JavaScript, so a palette drops
 * straight into a stylesheet under the `--color-*` namespace and every utility
 * (`bg-primary-600`, `text-danger-700`) follows from it.
 */

import type { Palette } from '../types.ts'
import { formatOklch, slug } from './shared.ts'

export interface TailwindOptions {
  /** OKLCH matches how Tailwind v4 writes its own palette. */
  mode?: 'oklch' | 'hex'
}

export function exportTailwindTheme(palette: Palette, options: TailwindOptions = {}): string {
  const mode = options.mode ?? 'oklch'

  const lines: string[] = [
    '/* Generated by Science Color Palette — paste into your Tailwind v4 stylesheet. */',
    '@theme {',
  ]

  for (const ramp of palette.ramps) {
    lines.push(`  /* ${ramp.name} */`)
    for (const swatch of ramp.swatches) {
      const value = mode === 'hex' ? swatch.hex : formatOklch(swatch.oklch)
      lines.push(`  --color-${slug(ramp.name)}-${swatch.label}: ${value};`)
    }
  }

  lines.push('}')
  return lines.join('\n') + '\n'
}
